//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

library openapi.api;

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:collection/collection.dart';
import 'package:http/http.dart';
import 'package:intl/intl.dart';
import 'package:meta/meta.dart';

part 'api_client.dart';
part 'api_helper.dart';
part 'api_exception.dart';
part 'auth/authentication.dart';
part 'auth/api_key_auth.dart';
part 'auth/oauth.dart';
part 'auth/http_basic_auth.dart';
part 'auth/http_bearer_auth.dart';

part 'api/analytics_api.dart';
part 'api/authentication_api.dart';
part 'api/balance_api.dart';
part 'api/checkouts_api.dart';
part 'api/compliance_api.dart';
part 'api/customers_api.dart';
part 'api/events_api.dart';
part 'api/health_api.dart';
part 'api/notifications_api.dart';
part 'api/payment_intents_api.dart';
part 'api/payment_links_api.dart';
part 'api/payment_methods_api.dart';
part 'api/payouts_api.dart';
part 'api/products_api.dart';
part 'api/purchases_api.dart';
part 'api/storage_api.dart';
part 'api/transfers_api.dart';
part 'api/webhooks_api.dart';

part 'model/accept_invitation_dto.dart';
part 'model/accept_invitation_response_dto.dart';
part 'model/admin_create_user_dto.dart';
part 'model/admin_create_user_response_dto.dart';
part 'model/admin_get_user_dto.dart';
part 'model/admin_get_user_response_dto.dart';
part 'model/admin_list_user_sessions_dto.dart';
part 'model/admin_list_user_sessions_response_dto.dart';
part 'model/admin_remove_user_dto.dart';
part 'model/admin_remove_user_response_dto.dart';
part 'model/admin_revoke_user_session_dto.dart';
part 'model/admin_revoke_user_session_response_dto.dart';
part 'model/admin_revoke_user_sessions_dto.dart';
part 'model/admin_revoke_user_sessions_response_dto.dart';
part 'model/admin_set_user_password_dto.dart';
part 'model/admin_set_user_password_response_dto.dart';
part 'model/admin_update_user_dto.dart';
part 'model/admin_update_user_response_dto.dart';
part 'model/analytics_response_dto.dart';
part 'model/analytics_summary_dto.dart';
part 'model/api_key.dart';
part 'model/balance_history_response_dto.dart';
part 'model/balance_transaction_dto.dart';
part 'model/ban_user_dto.dart';
part 'model/ban_user_response_dto.dart';
part 'model/base_dto.dart';
part 'model/cancel_invitation_dto.dart';
part 'model/cancel_invitation_response_dto.dart';
part 'model/change_email_dto.dart';
part 'model/change_email_response_dto.dart';
part 'model/change_password_dto.dart';
part 'model/change_password_response_dto.dart';
part 'model/check_slug_dto.dart';
part 'model/check_slug_response_dto.dart';
part 'model/checkout_session_response_dto.dart';
part 'model/confirm_upload_dto.dart';
part 'model/create_api_key_dto.dart';
part 'model/create_api_key_response_dto.dart';
part 'model/create_balance_dto.dart';
part 'model/create_checkout_session_dto.dart';
part 'model/create_customer_dto.dart';
part 'model/create_organization_compliance_dto.dart';
part 'model/create_organization_dto.dart';
part 'model/create_organization_response_dto.dart';
part 'model/create_payment_intent_dto.dart';
part 'model/create_payment_link_dto.dart';
part 'model/create_payment_method_dto.dart';
part 'model/create_payout_dto.dart';
part 'model/create_product_dto.dart';
part 'model/create_purchase_dto.dart';
part 'model/create_transfer_dto.dart';
part 'model/create_webhook_endpoint_dto.dart';
part 'model/customer_balance_dto.dart';
part 'model/customer_payment_method_dto.dart';
part 'model/customer_response_dto.dart';
part 'model/customer_stats_dto.dart';
part 'model/customer_transaction_dto.dart';
part 'model/daily_breakdown_dto.dart';
part 'model/debit_return_response_dto.dart';
part 'model/delete_api_key_dto.dart';
part 'model/delete_api_key_response_dto.dart';
part 'model/delete_organization_dto.dart';
part 'model/delete_organization_response_dto.dart';
part 'model/delete_user_dto.dart';
part 'model/delete_user_response_dto.dart';
part 'model/error_response_dto.dart';
part 'model/event_response_dto.dart';
part 'model/evervault_encrypted_card_dto.dart';
part 'model/file_dto.dart';
part 'model/forgot_password_dto.dart';
part 'model/forgot_password_response_dto.dart';
part 'model/get_access_token_dto.dart';
part 'model/get_access_token_response_dto.dart';
part 'model/get_active_member_response_dto.dart';
part 'model/get_active_member_role_response_dto.dart';
part 'model/get_api_key_response_dto.dart';
part 'model/get_full_organization_response_dto.dart';
part 'model/get_invitation_response_dto.dart';
part 'model/get_session_response_dto.dart';
part 'model/has_permission_dto.dart';
part 'model/has_permission_response_dto.dart';
part 'model/i_veri_health_check_response_dto.dart';
part 'model/impersonate_user_dto.dart';
part 'model/impersonate_user_response_dto.dart';
part 'model/initiate_payment_dto.dart';
part 'model/initiate_payment_response_dto.dart';
part 'model/invitation_dto.dart';
part 'model/invite_member_dto.dart';
part 'model/invite_member_response_dto.dart';
part 'model/is_username_available_dto.dart';
part 'model/is_username_available_response_dto.dart';
part 'model/iveri_params_dto.dart';
part 'model/leave_organization_dto.dart';
part 'model/leave_organization_response_dto.dart';
part 'model/line_item_dto.dart';
part 'model/link_social_dto.dart';
part 'model/link_social_response_dto.dart';
part 'model/list_accounts_response_dto.dart';
part 'model/list_api_keys_response_dto.dart';
part 'model/list_checkout_sessions_response_dto.dart';
part 'model/list_customer_payment_methods_response_dto.dart';
part 'model/list_customer_transactions_response_dto.dart';
part 'model/list_customers_response_dto.dart';
part 'model/list_events_response_dto.dart';
part 'model/list_files_response_dto.dart';
part 'model/list_invitations_response_dto.dart';
part 'model/list_members_response_dto.dart';
part 'model/list_organization_compliance_response_dto.dart';
part 'model/list_payment_intents_response_dto.dart';
part 'model/list_payment_links_response_dto.dart';
part 'model/list_payment_methods_response_dto.dart';
part 'model/list_payouts_response_dto.dart';
part 'model/list_products_response_dto.dart';
part 'model/list_sessions_response_dto.dart';
part 'model/list_transfers_response_dto.dart';
part 'model/list_user_invitations_response_dto.dart';
part 'model/list_users_response_dto.dart';
part 'model/list_webhook_endpoints_response_dto.dart';
part 'model/member_dto.dart';
part 'model/merchant_balance_response_dto.dart';
part 'model/metric_stats_dto.dart';
part 'model/notification_dto.dart';
part 'model/organization_compliance_response_dto.dart';
part 'model/organization_dto.dart';
part 'model/pagination_response_dto.dart';
part 'model/payment_intent_response_dto.dart';
part 'model/payment_link_response_dto.dart';
part 'model/payment_method_response_dto.dart';
part 'model/payout_response_dto.dart';
part 'model/presigned_download_response_dto.dart';
part 'model/presigned_upload_response_dto.dart';
part 'model/product_response_dto.dart';
part 'model/purchase_response_dto.dart';
part 'model/refresh_token_dto.dart';
part 'model/refresh_token_response_dto.dart';
part 'model/reject_invitation_dto.dart';
part 'model/reject_invitation_response_dto.dart';
part 'model/remove_member_dto.dart';
part 'model/remove_member_response_dto.dart';
part 'model/request_password_reset_dto.dart';
part 'model/request_password_reset_response_dto.dart';
part 'model/request_phone_password_reset_dto.dart';
part 'model/request_phone_password_reset_response_dto.dart';
part 'model/request_upload_url_dto.dart';
part 'model/reset_password_callback_response_dto.dart';
part 'model/reset_password_dto.dart';
part 'model/reset_password_response_dto.dart';
part 'model/reset_phone_password_dto.dart';
part 'model/reset_phone_password_response_dto.dart';
part 'model/revoke_session_dto.dart';
part 'model/revoke_session_response_dto.dart';
part 'model/send_email200_response.dart';
part 'model/send_email_dto.dart';
part 'model/send_multi_channel_notification200_response.dart';
part 'model/send_phone_otp_dto.dart';
part 'model/send_phone_otp_response_dto.dart';
part 'model/send_sms200_response.dart';
part 'model/send_sms_dto.dart';
part 'model/send_verification_email_dto.dart';
part 'model/send_verification_email_response_dto.dart';
part 'model/session_dto.dart';
part 'model/session_user_dto.dart';
part 'model/set_active_organization_dto.dart';
part 'model/set_active_organization_response_dto.dart';
part 'model/set_role_dto.dart';
part 'model/set_role_response_dto.dart';
part 'model/sign_in_dto.dart';
part 'model/sign_in_phone_number_dto.dart';
part 'model/sign_in_response_dto.dart';
part 'model/sign_out_response_dto.dart';
part 'model/sign_up_dto.dart';
part 'model/sign_up_response_dto.dart';
part 'model/social_sign_in_dto.dart';
part 'model/stop_impersonating_response_dto.dart';
part 'model/timeframe_metrics_dto.dart';
part 'model/transfer_response_dto.dart';
part 'model/unban_user_dto.dart';
part 'model/unban_user_response_dto.dart';
part 'model/unlink_account_dto.dart';
part 'model/unlink_account_response_dto.dart';
part 'model/update_api_key_dto.dart';
part 'model/update_api_key_response_dto.dart';
part 'model/update_balance_dto.dart';
part 'model/update_customer_dto.dart';
part 'model/update_member_role_dto.dart';
part 'model/update_member_role_response_dto.dart';
part 'model/update_organization_compliance_dto.dart';
part 'model/update_organization_dto.dart';
part 'model/update_organization_response_dto.dart';
part 'model/update_payment_link_dto.dart';
part 'model/update_payout_dto.dart';
part 'model/update_product_dto.dart';
part 'model/update_user_dto.dart';
part 'model/update_user_response_dto.dart';
part 'model/update_webhook_endpoint_dto.dart';
part 'model/verify_api_key_dto.dart';
part 'model/verify_api_key_response_dto.dart';
part 'model/verify_email_response_dto.dart';
part 'model/verify_phone_number_dto.dart';
part 'model/verify_phone_number_response_dto.dart';
part 'model/webhook_endpoint_response_dto.dart';


/// An [ApiClient] instance that uses the default values obtained from
/// the OpenAPI specification file.
var defaultApiClient = ApiClient();

const _delimiters = {'csv': ',', 'ssv': ' ', 'tsv': '\t', 'pipes': '|'};
const _dateEpochMarker = 'epoch';
const _deepEquality = DeepCollectionEquality();
final _dateFormatter = DateFormat('yyyy-MM-dd');
final _regList = RegExp(r'^List<(.*)>$');
final _regSet = RegExp(r'^Set<(.*)>$');
final _regMap = RegExp(r'^Map<String,(.*)>$');

bool _isEpochMarker(String? pattern) => pattern == _dateEpochMarker || pattern == '/$_dateEpochMarker/';
